/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * EOM_eq.c
 *
 * Code generation for function 'EOM_eq'
 *
 */

/* Include files */
#include "EOM_eq.h"
#include "EOM_eq_data.h"
#include "EOM_eq_types.h"
#include "massF1.h"
#include "massF2.h"
#include "rt_nonfinite.h"
#include "sprdmpF10.h"
#include "sqrt.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = {
    9,        /* lineNo */
    "EOM_eq", /* fcnName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\EOM_eq.m" /* pathName */
};

static emlrtRSInfo c_emlrtRSI = {
    29,       /* lineNo */
    "EOM_eq", /* fcnName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\EOM_eq.m" /* pathName */
};

static emlrtRSInfo e_emlrtRSI = {
    41,       /* lineNo */
    "EOM_eq", /* fcnName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\EOM_eq.m" /* pathName */
};

static emlrtRSInfo g_emlrtRSI = {
    57,       /* lineNo */
    "EOM_eq", /* fcnName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\EOM_eq.m" /* pathName */
};

static emlrtBCInfo emlrtBCI = {
    1,                        /* iFirst */
    1109,                     /* iLast */
    9,                        /* lineNo */
    34,                       /* colNo */
    "par_mex.user_pars.f_ex", /* aName */
    "static_mid_step",        /* fName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\static_mid_step.m", /* pName */
    0 /* checkKind */
};

static emlrtDCInfo emlrtDCI = {
    9,                 /* lineNo */
    34,                /* colNo */
    "static_mid_step", /* fName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\static_mid_step.m", /* pName */
    1 /* checkKind */
};

/* Function Definitions */
void EOM_eq(const emlrtStack *sp, const real_T z[9], creal_T res[9])
{
  static const int8_T iv[6] = {0, 0, 1, 1, 2, 2};
  emlrtStack st;
  creal_T Dd[54];
  creal_T T[54];
  creal_T Tt[54];
  creal_T b_Dd[54];
  creal_T b_T[54];
  creal_T b_Tt[54];
  creal_T c_T[54];
  creal_T c_M[36];
  creal_T TMfd[9];
  creal_T c_z[9];
  creal_T w_in[9];
  creal_T w_sd[9];
  creal_T b_kx[6];
  creal_T kx[6];
  creal_T vd[6];
  creal_T t49;
  real_T M[36];
  real_T b_M[36];
  real_T b_z[18];
  real_T b_fg[6];
  real_T b_in[6];
  real_T fg[6];
  real_T in[6];
  real_T b_re_tmp_tmp;
  real_T b_sn;
  real_T re_tmp_tmp;
  real_T step;
  real_T t10;
  real_T t11;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t27;
  real_T t30;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t39;
  real_T t39_tmp;
  real_T t4;
  real_T t43;
  real_T t44;
  real_T t45;
  real_T t46;
  real_T t46_tmp;
  real_T t47;
  real_T t5;
  real_T t50_im;
  real_T t50_re;
  real_T t54_im;
  real_T t54_re;
  real_T t56_im;
  real_T t56_re;
  real_T t60_im;
  real_T t60_re;
  real_T t61_im;
  real_T t61_re;
  real_T t62_im;
  real_T t62_re;
  real_T t9;
  int32_T T_re_tmp;
  int32_T i;
  int32_T i1;
  int32_T i2;
  int32_T sn;
  st.prev = sp;
  st.tls = sp->tls;
  for (i = 0; i < 9; i++) {
    step = z[i];
    b_z[i] = step;
    b_z[i + 9] = 0.0 * step;
  }
  st.site = &emlrtRSI;
  /*  parameters */
  /*  inputs: internal pressure & external forces/torques */
  /*  temp = interp1( par.f_ex(:,1) , [ par.f_ex(:,2:7) par.p(:,2:4) ] , t ,
   * 'nearest' ) ; */
  step = muDoubleScalarFloor(par_mex.t_equil_i / 0.05);
  if (step == 0.0) {
    step = 1.0;
  }
  if (step != (int32_T)step) {
    emlrtIntegerCheckR2012b(step, &emlrtDCI, &st);
  }
  if (((int32_T)step < 1) || ((int32_T)step > 1109)) {
    emlrtDynamicBoundsCheckR2012b((int32_T)step, 1, 1109, &emlrtBCI, &st);
  }
  /*  cross-section deformation */
  /*  In this case it causes numerical instability, so commented */
  /*  axial stretch */
  /*  l = 0 ; */
  /*  for i = 0 : par_mex.user_pars.n_l - 2 */
  /*      l = l + z(i*6+3) ; */
  /*  end */
  /*  lambda = 1 + l / par_mex.var(5) ; */
  /*  update simulation parameters */
  for (i = 0; i < 6; i++) {
    par_mex.var[i + 21] =
        par_mex.user_pars.p[((int32_T)step + 1109 * (iv[i] + 1)) - 1];
    par_mex.var[i + 27] =
        par_mex.user_pars.f_ex[((int32_T)step + 1109 * (i + 1)) - 1];
  }
  par_mex.var[33] = 1.0;
  par_mex_dirty |= 1U;
  /* romF */
  /*     [OUT1,OUT2] = romF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.1.
   */
  /*     07-Mar-2023 03:41:33 */
  t27 = par_mex.var[4];
  t50_im = par_mex.var[4];
  massF1(par_mex.var, b_z, 1.0E-6 * t27, M, T, Dd, fg);
  st.site = &c_emlrtRSI;
  sprdmpF10(&st, par_mex.var, b_z, 1.0E-6 * t50_im, Tt, kx, vd, in);
  massF1(par_mex.var, b_z, 0.999999 * t27, b_M, b_T, b_Dd, b_fg);
  st.site = &e_emlrtRSI;
  sprdmpF10(&st, par_mex.var, b_z, 0.999999 * t50_im, b_Tt, b_kx, vd, b_in);
  for (i = 0; i < 36; i++) {
    c_M[i].re = M[i];
    c_M[i].im = 0.0;
  }
  for (i = 0; i < 54; i++) {
    Dd[i].re = -Dd[i].re;
    Dd[i].im = -Dd[i].im;
  }
  for (i = 0; i < 9; i++) {
    c_z[i].re = b_z[i + 9];
    c_z[i].im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i2 = 0; i2 < 6; i2++) {
        T_re_tmp = i2 + 6 * i;
        step = T[T_re_tmp].re;
        t9 = -T[T_re_tmp].im;
        T_re_tmp = i2 + 6 * i1;
        t10 = c_M[T_re_tmp].im;
        t4 = c_M[T_re_tmp].re;
        t54_re += step * t4 - t9 * t10;
        t54_im += step * t10 + t9 * t4;
      }
      i2 = i + 9 * i1;
      c_T[i2].re = t54_re;
      c_T[i2].im = t54_im;
    }
  }
  for (i = 0; i < 6; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 9; i1++) {
      T_re_tmp = i + 6 * i1;
      step = Dd[T_re_tmp].re;
      t10 = c_z[i1].im;
      t4 = Dd[T_re_tmp].im;
      t9 = c_z[i1].re;
      t54_re += step * t9 - t4 * t10;
      t54_im += step * t10 + t4 * t9;
    }
    vd[i].re = t54_re + fg[i];
    vd[i].im = t54_im;
  }
  for (i = 0; i < 9; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      t10 = c_T[T_re_tmp].re;
      t4 = vd[i1].im;
      step = c_T[T_re_tmp].im;
      t9 = vd[i1].re;
      t54_re += t10 * t9 - step * t4;
      t54_im += t10 * t4 + step * t9;
    }
    TMfd[i].re = t54_re;
    TMfd[i].im = t54_im;
  }
  for (i = 0; i < 36; i++) {
    c_M[i].re = b_M[i];
    c_M[i].im = 0.0;
  }
  for (i = 0; i < 54; i++) {
    b_Dd[i].re = -b_Dd[i].re;
    b_Dd[i].im = -b_Dd[i].im;
  }
  for (i = 0; i < 9; i++) {
    c_z[i].re = b_z[i + 9];
    c_z[i].im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i2 = 0; i2 < 6; i2++) {
        T_re_tmp = i2 + 6 * i;
        step = b_T[T_re_tmp].re;
        t9 = -b_T[T_re_tmp].im;
        T_re_tmp = i2 + 6 * i1;
        t10 = c_M[T_re_tmp].im;
        t4 = c_M[T_re_tmp].re;
        t54_re += step * t4 - t9 * t10;
        t54_im += step * t10 + t9 * t4;
      }
      i2 = i + 9 * i1;
      c_T[i2].re = t54_re;
      c_T[i2].im = t54_im;
    }
  }
  for (i = 0; i < 6; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 9; i1++) {
      T_re_tmp = i + 6 * i1;
      step = b_Dd[T_re_tmp].re;
      t10 = c_z[i1].im;
      t4 = b_Dd[T_re_tmp].im;
      t9 = c_z[i1].re;
      t54_re += step * t9 - t4 * t10;
      t54_im += step * t10 + t4 * t9;
    }
    vd[i].re = t54_re + b_fg[i];
    vd[i].im = t54_im;
  }
  for (i = 0; i < 9; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      t10 = c_T[T_re_tmp].re;
      t4 = vd[i1].im;
      step = c_T[T_re_tmp].im;
      t9 = vd[i1].re;
      t54_re += t10 * t9 - step * t4;
      t54_im += t10 * t4 + step * t9;
    }
    t9 = TMfd[i].re * par_mex.var[4] + t54_re * t27;
    step = TMfd[i].im * par_mex.var[4] + t54_im * t27;
    if (step == 0.0) {
      t54_re = t9 / 2.0;
      t54_im = 0.0;
    } else if (t9 == 0.0) {
      t54_re = 0.0;
      t54_im = step / 2.0;
    } else {
      t54_re = t9 / 2.0;
      t54_im = step / 2.0;
    }
    TMfd[i].re = t54_re;
    TMfd[i].im = t54_im;
    t54_re = 0.0;
    t54_im = 0.0;
    step = 0.0;
    t11 = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      t9 = Tt[T_re_tmp].re;
      t10 = kx[i1].im;
      t4 = Tt[T_re_tmp].im;
      b_sn = kx[i1].re;
      t54_re += t9 * b_sn - t4 * t10;
      t54_im += t9 * t10 + t4 * b_sn;
      t9 = b_Tt[T_re_tmp].re;
      t10 = b_kx[i1].im;
      t4 = b_Tt[T_re_tmp].im;
      b_sn = b_kx[i1].re;
      step += t9 * b_sn - t4 * t10;
      t11 += t9 * t10 + t4 * b_sn;
    }
    t9 = t54_re * par_mex.var[4] + step * par_mex.var[4];
    step = t54_im * par_mex.var[4] + t11 * par_mex.var[4];
    if (step == 0.0) {
      w_sd[i].re = t9 / 2.0;
      w_sd[i].im = 0.0;
    } else if (t9 == 0.0) {
      w_sd[i].re = 0.0;
      w_sd[i].im = step / 2.0;
    } else {
      w_sd[i].re = t9 / 2.0;
      w_sd[i].im = step / 2.0;
    }
  }
  for (i = 0; i < 6; i++) {
    vd[i].re = in[i];
    vd[i].im = 0.0;
  }
  for (i = 0; i < 9; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      t9 = Tt[T_re_tmp].re;
      t10 = vd[i1].im;
      t4 = Tt[T_re_tmp].im;
      b_sn = vd[i1].re;
      t54_re += t9 * b_sn - t4 * t10;
      t54_im += t9 * t10 + t4 * b_sn;
    }
    w_in[i].re = t54_re;
    w_in[i].im = t54_im;
  }
  for (i = 0; i < 6; i++) {
    vd[i].re = b_in[i];
    vd[i].im = 0.0;
  }
  for (i = 0; i < 9; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      t9 = b_Tt[T_re_tmp].re;
      t10 = vd[i1].im;
      t4 = b_Tt[T_re_tmp].im;
      b_sn = vd[i1].re;
      t54_re += t9 * b_sn - t4 * t10;
      t54_im += t9 * t10 + t4 * b_sn;
    }
    t9 = w_in[i].re * par_mex.var[4] + t54_re * par_mex.var[4];
    step = w_in[i].im * par_mex.var[4] + t54_im * par_mex.var[4];
    if (step == 0.0) {
      t54_re = t9 / 2.0;
      t54_im = 0.0;
    } else if (t9 == 0.0) {
      t54_re = 0.0;
      t54_im = step / 2.0;
    } else {
      t54_re = t9 / 2.0;
      t54_im = step / 2.0;
    }
    w_in[i].re = t54_re;
    w_in[i].im = t54_im;
  }
  for (sn = 0; sn < 9; sn++) {
    b_sn = (real_T)sn * 0.1 + 0.100001;
    massF1(par_mex.var, b_z, b_sn * t27, M, T, Dd, fg);
    for (i = 0; i < 36; i++) {
      c_M[i].re = M[i];
      c_M[i].im = 0.0;
    }
    for (i = 0; i < 54; i++) {
      Dd[i].re = -Dd[i].re;
      Dd[i].im = -Dd[i].im;
    }
    for (i = 0; i < 9; i++) {
      c_z[i].re = b_z[i + 9];
      c_z[i].im = 0.0;
      for (i1 = 0; i1 < 6; i1++) {
        t54_re = 0.0;
        t54_im = 0.0;
        for (i2 = 0; i2 < 6; i2++) {
          T_re_tmp = i2 + 6 * i;
          step = T[T_re_tmp].re;
          t9 = -T[T_re_tmp].im;
          T_re_tmp = i2 + 6 * i1;
          t10 = c_M[T_re_tmp].im;
          t4 = c_M[T_re_tmp].re;
          t54_re += step * t4 - t9 * t10;
          t54_im += step * t10 + t9 * t4;
        }
        i2 = i + 9 * i1;
        c_T[i2].re = t54_re;
        c_T[i2].im = t54_im;
      }
    }
    for (i = 0; i < 6; i++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i1 = 0; i1 < 9; i1++) {
        T_re_tmp = i + 6 * i1;
        step = Dd[T_re_tmp].re;
        t10 = c_z[i1].im;
        t4 = Dd[T_re_tmp].im;
        t9 = c_z[i1].re;
        t54_re += step * t9 - t4 * t10;
        t54_im += step * t10 + t4 * t9;
      }
      vd[i].re = t54_re + fg[i];
      vd[i].im = t54_im;
    }
    for (i = 0; i < 9; i++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i1 = 0; i1 < 6; i1++) {
        T_re_tmp = i + 9 * i1;
        t10 = c_T[T_re_tmp].re;
        t4 = vd[i1].im;
        step = c_T[T_re_tmp].im;
        t9 = vd[i1].re;
        t54_re += t10 * t9 - step * t4;
        t54_im += t10 * t4 + step * t9;
      }
      TMfd[i].re += t54_re * t27;
      TMfd[i].im += t54_im * t27;
    }
    st.site = &g_emlrtRSI;
    sprdmpF10(&st, par_mex.var, b_z, b_sn * t50_im, Tt, kx, vd, in);
    for (i = 0; i < 9; i++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i1 = 0; i1 < 6; i1++) {
        T_re_tmp = i + 9 * i1;
        t9 = Tt[T_re_tmp].re;
        t10 = kx[i1].im;
        t4 = Tt[T_re_tmp].im;
        b_sn = kx[i1].re;
        t54_re += t9 * b_sn - t4 * t10;
        t54_im += t9 * t10 + t4 * b_sn;
      }
      w_sd[i].re += t54_re * par_mex.var[4];
      w_sd[i].im += t54_im * par_mex.var[4];
    }
    for (i = 0; i < 6; i++) {
      vd[i].re = in[i];
      vd[i].im = 0.0;
    }
    for (i = 0; i < 9; i++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i1 = 0; i1 < 6; i1++) {
        T_re_tmp = i + 9 * i1;
        t9 = Tt[T_re_tmp].re;
        t10 = vd[i1].im;
        t4 = Tt[T_re_tmp].im;
        b_sn = vd[i1].re;
        t54_re += t9 * b_sn - t4 * t10;
        t54_im += t9 * t10 + t4 * b_sn;
      }
      w_in[i].re += t54_re * par_mex.var[4];
      w_in[i].im += t54_im * par_mex.var[4];
    }
    if (*emlrtBreakCheckR2012bFlagVar != 0) {
      emlrtBreakCheckR2012b((emlrtCTX)sp);
    }
  }
  for (i = 0; i < 9; i++) {
    t9 = TMfd[i].re;
    step = TMfd[i].im;
    if (step == 0.0) {
      t54_re = t9 / 10.0;
      t54_im = 0.0;
    } else if (t9 == 0.0) {
      t54_re = 0.0;
      t54_im = step / 10.0;
    } else {
      t54_re = t9 / 10.0;
      t54_im = step / 10.0;
    }
    TMfd[i].re = t54_re;
    TMfd[i].im = t54_im;
    t9 = w_sd[i].re;
    step = w_sd[i].im;
    if (step == 0.0) {
      t54_re = t9 / 10.0;
      t54_im = 0.0;
    } else if (t9 == 0.0) {
      t54_re = 0.0;
      t54_im = step / 10.0;
    } else {
      t54_re = t9 / 10.0;
      t54_im = step / 10.0;
    }
    w_sd[i].re = t54_re;
    w_sd[i].im = t54_im;
    t9 = w_in[i].re;
    step = w_in[i].im;
    if (step == 0.0) {
      t54_re = t9 / 10.0;
      t54_im = 0.0;
    } else if (t9 == 0.0) {
      t54_re = 0.0;
      t54_im = step / 10.0;
    } else {
      t54_re = t9 / 10.0;
      t54_im = step / 10.0;
    }
    w_in[i].re = t54_re;
    w_in[i].im = t54_im;
  }
  massF2(par_mex.var, b_z, M, T, Dd, fg);
  for (i = 0; i < 36; i++) {
    c_M[i].re = M[i];
    c_M[i].im = 0.0;
  }
  for (i = 0; i < 54; i++) {
    Dd[i].re = -Dd[i].re;
    Dd[i].im = -Dd[i].im;
  }
  for (i = 0; i < 9; i++) {
    c_z[i].re = b_z[i + 9];
    c_z[i].im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      t54_re = 0.0;
      t54_im = 0.0;
      for (i2 = 0; i2 < 6; i2++) {
        T_re_tmp = i2 + 6 * i;
        step = T[T_re_tmp].re;
        t9 = -T[T_re_tmp].im;
        T_re_tmp = i2 + 6 * i1;
        t10 = c_M[T_re_tmp].im;
        t4 = c_M[T_re_tmp].re;
        t54_re += step * t4 - t9 * t10;
        t54_im += step * t10 + t9 * t4;
      }
      i2 = i + 9 * i1;
      c_T[i2].re = t54_re;
      c_T[i2].im = t54_im;
    }
  }
  for (i = 0; i < 6; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 9; i1++) {
      T_re_tmp = i + 6 * i1;
      step = Dd[T_re_tmp].re;
      t10 = c_z[i1].im;
      t4 = Dd[T_re_tmp].im;
      t9 = c_z[i1].re;
      t54_re += step * t9 - t4 * t10;
      t54_im += step * t10 + t4 * t9;
    }
    vd[i].re = t54_re + fg[i];
    vd[i].im = t54_im;
  }
  for (i = 0; i < 9; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      t10 = c_T[T_re_tmp].re;
      t4 = vd[i1].im;
      step = c_T[T_re_tmp].im;
      t9 = vd[i1].re;
      t54_re += t10 * t9 - step * t4;
      t54_im += t10 * t4 + step * t9;
    }
    TMfd[i].re += t54_re;
    TMfd[i].im += t54_im;
  }
  /* loadsF1 */
  /*     [OUT1,OUT2,OUT3] = loadsF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.1.
   */
  /*     07-Mar-2023 03:42:32 */
  step = b_z[3] * par_mex.var[4];
  b_sn = par_mex.var[4] * b_z[5];
  t4 = par_mex.var[4] * b_z[7];
  t5 = par_mex.var[4] * par_mex.var[4];
  t9 = b_z[4] * t5;
  t10 = b_z[6] * t5;
  t11 = b_z[8] * t5;
  t15 = step + t9;
  t16 = b_sn + t10;
  t17 = t4 + t11;
  t27 = step * 2.0 + t9 * 2.0;
  t9 = b_sn * 2.0 + t10 * 2.0;
  step = t4 * 2.0 + t11 * 2.0;
  t30 = t15 * t15;
  b_sn = t16 * t16;
  t39_tmp = par_mex.var[4] * par_mex.var[16];
  t39 = t39_tmp * t17 * 2.0;
  t46_tmp = par_mex.var[16] * t5;
  t46 = t46_tmp * t17 * 2.0;
  t33 = par_mex.var[4] * t27;
  t34 = par_mex.var[4] * t9;
  t35 = par_mex.var[4] * step;
  t43 = t5 * t27;
  t44 = t5 * t9;
  t45 = t5 * step;
  t47 = (t15 * par_mex.var[30] + t16 * par_mex.var[31]) + t17 * par_mex.var[32];
  t49.re = ((-t30 + -b_sn) + -(t17 * t17)) + 1.0;
  t49.im = 0.0;
  b_sqrt(&t49);
  if (t49.im == 0.0) {
    t50_re = 1.0 / t49.re;
    t50_im = 0.0;
  } else if (t49.re == 0.0) {
    t50_re = 0.0;
    t50_im = -(1.0 / t49.im);
  } else {
    t10 = muDoubleScalarAbs(t49.re);
    step = muDoubleScalarAbs(t49.im);
    if (t10 > step) {
      step = t49.im / t49.re;
      t9 = t49.re + step * t49.im;
      t50_re = (step * 0.0 + 1.0) / t9;
      t50_im = (0.0 - step) / t9;
    } else if (step == t10) {
      if (t49.re > 0.0) {
        step = 0.5;
      } else {
        step = -0.5;
      }
      if (t49.im > 0.0) {
        t9 = 0.5;
      } else {
        t9 = -0.5;
      }
      t50_re = (step + 0.0 * t9) / t10;
      t50_im = (0.0 * step - t9) / t10;
    } else {
      step = t49.re / t49.im;
      t9 = t49.im + step * t49.re;
      t50_re = step / t9;
      t50_im = (step * 0.0 - 1.0) / t9;
    }
  }
  t54_re = 2.0 * (par_mex.var[4] * t49.re);
  t54_im = 2.0 * (par_mex.var[4] * t49.im);
  t56_re = 2.0 * (t5 * t49.re);
  t56_im = 2.0 * (t5 * t49.im);
  re_tmp_tmp = t39_tmp * t15;
  step = re_tmp_tmp * t16;
  t9 = 2.0 * (step * t50_re);
  t10 = 2.0 * (step * t50_im);
  b_re_tmp_tmp = t46_tmp * t15;
  step = b_re_tmp_tmp * t16;
  t4 = 2.0 * (step * t50_re);
  t11 = 2.0 * (step * t50_im);
  t60_re = (t16 * par_mex.var[30] + -(t15 * par_mex.var[31])) +
           t49.re * par_mex.var[32];
  t60_im = t49.im * par_mex.var[32];
  t61_re = (t15 * par_mex.var[32] + -(t17 * par_mex.var[30])) +
           t49.re * par_mex.var[31];
  t61_im = t49.im * par_mex.var[31];
  t62_re = (t17 * par_mex.var[31] + -(t16 * par_mex.var[32])) +
           t49.re * par_mex.var[30];
  t62_im = t49.im * par_mex.var[30];
  /*  EOM */
  T[0].re = t5;
  T[0].im = 0.0;
  T[1].re = 0.0;
  T[1].im = 0.0;
  T[2].re = 0.0;
  T[2].im = 0.0;
  T[3].re = t39 - t9;
  T[3].im = 0.0 - t10;
  T[4].re = t46 - t4;
  T[4].im = 0.0 - t11;
  step = t39_tmp * b_sn;
  T[5].re = par_mex.var[16] * t54_re - step * t50_re * 2.0;
  T[5].im = par_mex.var[16] * t54_im - step * t50_im * 2.0;
  step = t46_tmp * b_sn;
  T[6].re = par_mex.var[16] * t56_re - step * t50_re * 2.0;
  T[6].im = par_mex.var[16] * t56_im - step * t50_im * 2.0;
  b_sn = t39_tmp * t16;
  step = b_sn * t17;
  T[7].re = re_tmp_tmp * 2.0 - step * t50_re * 2.0;
  T[7].im = 0.0 - step * t50_im * 2.0;
  t27 = t46_tmp * t16;
  step = t27 * t17;
  T[8].re = b_re_tmp_tmp * 2.0 - step * t50_re * 2.0;
  T[8].im = 0.0 - step * t50_im * 2.0;
  T[9].re = 0.0;
  T[9].im = 0.0;
  T[10].re = t5;
  T[10].im = 0.0;
  T[11].re = 0.0;
  T[11].im = 0.0;
  step = t39_tmp * t30;
  T[12].re = t39_tmp * t49.re * -2.0 + step * t50_re * 2.0;
  T[12].im = t39_tmp * t49.im * -2.0 + step * t50_im * 2.0;
  step = t46_tmp * t30;
  T[13].re = t46_tmp * t49.re * -2.0 + step * t50_re * 2.0;
  T[13].im = t46_tmp * t49.im * -2.0 + step * t50_im * 2.0;
  T[14].re = t39 + t9;
  T[14].im = t10;
  T[15].re = t46 + t4;
  T[15].im = t11;
  step = t15 * t39;
  T[16].re = b_sn * 2.0 + step * t50_re;
  T[16].im = step * t50_im;
  step = t15 * t46;
  T[17].re = t27 * 2.0 + step * t50_re;
  T[17].im = step * t50_im;
  T[18].re = 0.0;
  T[18].im = 0.0;
  T[19].re = 0.0;
  T[19].im = 0.0;
  T[20].re = t5;
  T[20].im = 0.0;
  T[21].re = re_tmp_tmp * -4.0;
  T[21].im = 0.0;
  T[22].re = b_re_tmp_tmp * -4.0;
  T[22].im = 0.0;
  T[23].re = b_sn * -4.0;
  T[23].im = 0.0;
  T[24].re = t27 * -4.0;
  T[24].im = 0.0;
  T[25].re = 0.0;
  T[25].im = 0.0;
  T[26].re = 0.0;
  T[26].im = 0.0;
  T[27].re = 0.0;
  T[27].im = 0.0;
  T[28].re = 0.0;
  T[28].im = 0.0;
  T[29].re = 0.0;
  T[29].im = 0.0;
  step = t15 * t33;
  T[30].re = t54_re + step * t50_re;
  T[30].im = t54_im + step * t50_im;
  step = t15 * t43;
  T[31].re = t56_re + step * t50_re;
  T[31].im = t56_im + step * t50_im;
  step = t16 * t33;
  T[32].re = t35 + step * t50_re;
  T[32].im = step * t50_im;
  step = t16 * t43;
  T[33].re = t45 + step * t50_re;
  T[33].im = step * t50_im;
  step = t17 * t33;
  T[34].re = -t34 + step * t50_re;
  T[34].im = step * t50_im;
  step = t17 * t43;
  T[35].re = -t44 + step * t50_re;
  T[35].im = step * t50_im;
  T[36].re = 0.0;
  T[36].im = 0.0;
  T[37].re = 0.0;
  T[37].im = 0.0;
  T[38].re = 0.0;
  T[38].im = 0.0;
  step = t15 * t34;
  T[39].re = -t35 + step * t50_re;
  T[39].im = step * t50_im;
  step = t15 * t44;
  T[40].re = -t45 + step * t50_re;
  T[40].im = step * t50_im;
  step = t16 * t34;
  T[41].re = t54_re + step * t50_re;
  T[41].im = t54_im + step * t50_im;
  step = t16 * t44;
  T[42].re = t56_re + step * t50_re;
  T[42].im = t56_im + step * t50_im;
  step = t17 * t34;
  T[43].re = t33 + step * t50_re;
  T[43].im = step * t50_im;
  step = t17 * t44;
  T[44].re = t43 + step * t50_re;
  T[44].im = step * t50_im;
  T[45].re = 0.0;
  T[45].im = 0.0;
  T[46].re = 0.0;
  T[46].im = 0.0;
  T[47].re = 0.0;
  T[47].im = 0.0;
  step = t15 * t35;
  T[48].re = t34 + step * t50_re;
  T[48].im = step * t50_im;
  step = t15 * t45;
  T[49].re = t44 + step * t50_re;
  T[49].im = step * t50_im;
  step = t16 * t35;
  T[50].re = -t33 + step * t50_re;
  T[50].im = step * t50_im;
  step = t16 * t45;
  T[51].re = -t43 + step * t50_re;
  T[51].im = step * t50_im;
  step = t17 * t35;
  T[52].re = t54_re + step * t50_re;
  T[52].im = t54_im + step * t50_im;
  step = t17 * t45;
  T[53].re = t56_re + step * t50_re;
  T[53].im = t56_im + step * t50_im;
  vd[0].re = par_mex.var[27];
  vd[0].im = 0.0;
  vd[1].re = par_mex.var[28];
  vd[1].im = 0.0;
  vd[2].re = par_mex.var[29];
  vd[2].im = 0.0;
  vd[3].re = ((t15 * t47 - t16 * t60_re) + t17 * t61_re) +
             (t49.re * t62_re - t49.im * t62_im);
  vd[3].im = ((0.0 - t16 * t60_im) + t17 * t61_im) +
             (t49.re * t62_im + t49.im * t62_re);
  vd[4].re = ((t16 * t47 + t15 * t60_re) - t17 * t62_re) +
             (t49.re * t61_re - t49.im * t61_im);
  vd[4].im =
      (t15 * t60_im - t17 * t62_im) + (t49.re * t61_im + t49.im * t61_re);
  vd[5].re = ((t17 * t47 - t15 * t61_re) + t16 * t62_re) +
             (t49.re * t60_re - t49.im * t60_im);
  vd[5].im = ((0.0 - t15 * t61_im) + t16 * t62_im) +
             (t49.re * t60_im + t49.im * t60_re);
  for (i = 0; i < 9; i++) {
    t54_re = 0.0;
    t54_im = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      T_re_tmp = i + 9 * i1;
      step = T[T_re_tmp].re;
      t9 = vd[i1].im;
      t10 = T[T_re_tmp].im;
      t4 = vd[i1].re;
      t54_re += step * t4 - t10 * t9;
      t54_im += step * t9 + t10 * t4;
    }
    res[i].re = ((TMfd[i].re + w_sd[i].re) + w_in[i].re) + t54_re;
    res[i].im = ((TMfd[i].im + w_sd[i].im) + w_in[i].im) + t54_im;
  }
}

/* End of code generation (EOM_eq.c) */
