/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "massF1.h"
#include "EOM_eq_data.h"
#include "power.h"
#include "rt_nonfinite.h"
#include "sqrt.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void massF1(const real_T in1[34], const real_T in2[18], real_T s,
            real_T out1[36], creal_T out2[54], creal_T out3[54], real_T out4[6])
{
  creal_T t61;
  creal_T t62;
  creal_T t63;
  real_T t10;
  real_T t100_im;
  real_T t100_re;
  real_T t101_im;
  real_T t101_re;
  real_T t102_im;
  real_T t102_re;
  real_T t103_im;
  real_T t103_re;
  real_T t104_im;
  real_T t104_re;
  real_T t105_im;
  real_T t105_re;
  real_T t108_im;
  real_T t108_re;
  real_T t109_im;
  real_T t109_re;
  real_T t11;
  real_T t110_im;
  real_T t110_re;
  real_T t111_im;
  real_T t111_re;
  real_T t112_im;
  real_T t112_re;
  real_T t113_im;
  real_T t113_re;
  real_T t114_im;
  real_T t114_re;
  real_T t115_im;
  real_T t115_re;
  real_T t116_im;
  real_T t116_re;
  real_T t117_im;
  real_T t117_re;
  real_T t118_im;
  real_T t118_re;
  real_T t119_im;
  real_T t119_re;
  real_T t12;
  real_T t120_im;
  real_T t120_re;
  real_T t13;
  real_T t130_im;
  real_T t130_re;
  real_T t131_im;
  real_T t131_re;
  real_T t132_im;
  real_T t132_re;
  real_T t134_im;
  real_T t136_im;
  real_T t136_re;
  real_T t137_im;
  real_T t137_re;
  real_T t138_im;
  real_T t138_re;
  real_T t139_im;
  real_T t139_re;
  real_T t140_im;
  real_T t140_re;
  real_T t141_im;
  real_T t141_re;
  real_T t142_im;
  real_T t142_re;
  real_T t143_re;
  real_T t148_im;
  real_T t148_re;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t4;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t45;
  real_T t46;
  real_T t47;
  real_T t5;
  real_T t51;
  real_T t52;
  real_T t53;
  real_T t57;
  real_T t6;
  real_T t64_im;
  real_T t64_re;
  real_T t67_im;
  real_T t67_re;
  real_T t68_im;
  real_T t68_re;
  real_T t69_im;
  real_T t69_re;
  real_T t70_im;
  real_T t70_re;
  real_T t71_im;
  real_T t71_re;
  real_T t72_im;
  real_T t72_re;
  real_T t73_im;
  real_T t73_re;
  real_T t74_im;
  real_T t74_re;
  real_T t75_im;
  real_T t75_re;
  real_T t76_im;
  real_T t76_re;
  real_T t77_im;
  real_T t77_re;
  real_T t78_im;
  real_T t78_re;
  real_T t78_re_tmp;
  real_T t79_im;
  real_T t79_re;
  real_T t80_im;
  real_T t80_re;
  real_T t81_im;
  real_T t81_re;
  real_T t81_re_tmp;
  real_T t82_im;
  real_T t82_re;
  real_T t84_im;
  real_T t84_re;
  real_T t84_re_tmp;
  real_T t9;
  real_T t94_im;
  real_T t94_re;
  real_T t95_im;
  real_T t95_re;
  real_T t96_im;
  real_T t96_re;
  real_T t97_im;
  real_T t97_re;
  real_T t98_im;
  real_T t98_re;
  real_T t99_im;
  real_T t99_re;
  /* massF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = massF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.1.
   */
  /*     07-Mar-2023 03:42:23 */
  t148_re = muDoubleScalarCos(in1[20]);
  t148_im = muDoubleScalarSin(in1[20]);
  t4 = in2[3] * s;
  t5 = in2[5] * s;
  t6 = in2[7] * s;
  t9 = in1[2] * in1[2];
  t10 = in1[3] * in1[3];
  t11 = s * s;
  t12 = muDoubleScalarPower(s, 3.0);
  t13 = t11 * t11;
  t19 = in1[18] * in1[18] * 6.0;
  t20 = t11 * 2.0;
  t21 = t12 * 2.0;
  t22 = t13 * 2.0;
  t35 = t4 + in2[4] * t11;
  t36 = t5 + in2[6] * t11;
  t37 = t6 + in2[8] * t11;
  t38 = t4 * 2.0 + in2[4] * t20;
  t39 = t5 * 2.0 + in2[6] * t20;
  t40 = t6 * 2.0 + in2[8] * t20;
  t41 = t35 * t35;
  t42 = t36 * t36;
  t43 = t37 * t37;
  t45 = s * t38;
  t46 = s * t39;
  t47 = s * t40;
  t51 = t11 * t38;
  t52 = t11 * t39;
  t53 = t11 * t40;
  t57 = -(in1[0] * ((t9 + t19) + -t10) * 3.1415926535897931);
  t4 = (t10 + -t9) + t19 * (1.0 / (t148_im * t148_im)) *
                         (in1[33] * in1[33] * (t148_re * t148_re) - 1.0);
  t61.re = ((-t41 + -t42) + -t43) + 1.0;
  t61.im = 0.0;
  b_sqrt(&t61);
  t5 = in1[0] * (1.0 / in1[33]);
  t6 = t5 * (t9 / 4.0 + t10 / 4.0) * t4 * 3.1415926535897931;
  out1[0] = t57;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t57;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t57;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t6;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t6;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t5 * t4 * 3.1415926535897931 * (t9 / 2.0 + t10 / 2.0);
  if (t61.im == 0.0) {
    t62.re = 1.0 / t61.re;
    t62.im = 0.0;
  } else if (t61.re == 0.0) {
    t62.re = 0.0;
    t62.im = -(1.0 / t61.im);
  } else {
    t6 = muDoubleScalarAbs(t61.re);
    t4 = muDoubleScalarAbs(t61.im);
    if (t6 > t4) {
      t4 = t61.im / t61.re;
      t5 = t61.re + t4 * t61.im;
      t62.re = (t4 * 0.0 + 1.0) / t5;
      t62.im = (0.0 - t4) / t5;
    } else if (t4 == t6) {
      if (t61.re > 0.0) {
        t4 = 0.5;
      } else {
        t4 = -0.5;
      }
      if (t61.im > 0.0) {
        t5 = 0.5;
      } else {
        t5 = -0.5;
      }
      t62.re = (t4 + 0.0 * t5) / t6;
      t62.im = (0.0 * t4 - t5) / t6;
    } else {
      t4 = t61.re / t61.im;
      t5 = t61.im + t4 * t61.re;
      t62.re = t4 / t5;
      t62.im = (t4 * 0.0 - 1.0) / t5;
    }
  }
  t64_re = 2.0 * (s * t61.re);
  t64_im = 2.0 * (s * t61.im);
  t61.re *= t20;
  t61.im *= t20;
  t63 = power(t62);
  t4 = t20 * t35;
  t67_re = t4 * t62.re;
  t67_im = t4 * t62.im;
  t4 = t21 * t35;
  t68_re = t4 * t62.re;
  t68_im = t4 * t62.im;
  t4 = t22 * t35;
  t69_re = t4 * t62.re;
  t69_im = t4 * t62.im;
  t4 = t20 * t36;
  t70_re = t4 * t62.re;
  t70_im = t4 * t62.im;
  t4 = t21 * t36;
  t71_re = t4 * t62.re;
  t71_im = t4 * t62.im;
  t4 = t22 * t36;
  t72_re = t4 * t62.re;
  t72_im = t4 * t62.im;
  t4 = t20 * t37;
  t73_re = t4 * t62.re;
  t73_im = t4 * t62.im;
  t4 = t21 * t37;
  t74_re = t4 * t62.re;
  t74_im = t4 * t62.im;
  t4 = t22 * t37;
  t75_re = t4 * t62.re;
  t75_im = t4 * t62.im;
  t76_re = t51 * t62.re;
  t76_im = t51 * t62.im;
  t134_im = t12 * t38;
  t77_re = t134_im * t62.re;
  t77_im = t134_im * t62.im;
  t78_re_tmp = t13 * t38;
  t78_re = t78_re_tmp * t62.re;
  t78_im = t78_re_tmp * t62.im;
  t79_re = t52 * t62.re;
  t79_im = t52 * t62.im;
  t142_im = t12 * t39;
  t80_re = t142_im * t62.re;
  t80_im = t142_im * t62.im;
  t81_re_tmp = t13 * t39;
  t81_re = t81_re_tmp * t62.re;
  t81_im = t81_re_tmp * t62.im;
  t82_re = t53 * t62.re;
  t82_im = t53 * t62.im;
  out3[0].re = t11;
  out3[0].im = 0.0;
  out3[1].re = 0.0;
  out3[1].im = 0.0;
  out3[2].re = 0.0;
  out3[2].im = 0.0;
  out3[3].re = 0.0;
  out3[3].im = 0.0;
  out3[4].re = 0.0;
  out3[4].im = 0.0;
  out3[5].re = 0.0;
  out3[5].im = 0.0;
  out3[6].re = 0.0;
  out3[6].im = 0.0;
  out3[7].re = t11;
  out3[7].im = 0.0;
  out3[8].re = 0.0;
  out3[8].im = 0.0;
  out3[9].re = 0.0;
  out3[9].im = 0.0;
  out3[10].re = 0.0;
  out3[10].im = 0.0;
  out3[11].re = 0.0;
  out3[11].im = 0.0;
  out3[12].re = 0.0;
  out3[12].im = 0.0;
  out3[13].re = 0.0;
  out3[13].im = 0.0;
  out3[14].re = t11;
  out3[14].im = 0.0;
  out3[15].re = 0.0;
  out3[15].im = 0.0;
  out3[16].re = 0.0;
  out3[16].im = 0.0;
  out3[17].re = 0.0;
  out3[17].im = 0.0;
  out3[18].re = 0.0;
  out3[18].im = 0.0;
  out3[19].re = 0.0;
  out3[19].im = 0.0;
  out3[20].re = 0.0;
  out3[20].im = 0.0;
  t4 = t35 * t45;
  out3[21].re = t64_re + t4 * t62.re;
  out3[21].im = t64_im + t4 * t62.im;
  t4 = t35 * t46;
  out3[22].re = -t47 + t4 * t62.re;
  out3[22].im = t4 * t62.im;
  t4 = t35 * t47;
  out3[23].re = t46 + t4 * t62.re;
  out3[23].im = t4 * t62.im;
  out3[24].re = 0.0;
  out3[24].im = 0.0;
  out3[25].re = 0.0;
  out3[25].im = 0.0;
  out3[26].re = 0.0;
  out3[26].im = 0.0;
  out3[27].re = t61.re + t35 * t76_re;
  out3[27].im = t61.im + t35 * t76_im;
  out3[28].re = -t53 + t35 * t79_re;
  out3[28].im = t35 * t79_im;
  out3[29].re = t52 + t35 * t82_re;
  out3[29].im = t35 * t82_im;
  out3[30].re = 0.0;
  out3[30].im = 0.0;
  out3[31].re = 0.0;
  out3[31].im = 0.0;
  out3[32].re = 0.0;
  out3[32].im = 0.0;
  t4 = t36 * t45;
  out3[33].re = t47 + t4 * t62.re;
  out3[33].im = t4 * t62.im;
  t4 = t36 * t46;
  out3[34].re = t64_re + t4 * t62.re;
  out3[34].im = t64_im + t4 * t62.im;
  t4 = t36 * t47;
  out3[35].re = -t45 + t4 * t62.re;
  out3[35].im = t4 * t62.im;
  out3[36].re = 0.0;
  out3[36].im = 0.0;
  out3[37].re = 0.0;
  out3[37].im = 0.0;
  out3[38].re = 0.0;
  out3[38].im = 0.0;
  out3[39].re = t53 + t36 * t76_re;
  out3[39].im = t36 * t76_im;
  out3[40].re = t61.re + t36 * t79_re;
  out3[40].im = t61.im + t36 * t79_im;
  out3[41].re = -t51 + t36 * t82_re;
  out3[41].im = t36 * t82_im;
  out3[42].re = 0.0;
  out3[42].im = 0.0;
  out3[43].re = 0.0;
  out3[43].im = 0.0;
  out3[44].re = 0.0;
  out3[44].im = 0.0;
  t4 = t37 * t45;
  out3[45].re = -t46 + t4 * t62.re;
  out3[45].im = t4 * t62.im;
  t4 = t37 * t46;
  out3[46].re = t45 + t4 * t62.re;
  out3[46].im = t4 * t62.im;
  t4 = t37 * t47;
  out3[47].re = t64_re + t4 * t62.re;
  out3[47].im = t64_im + t4 * t62.im;
  out3[48].re = 0.0;
  out3[48].im = 0.0;
  out3[49].re = 0.0;
  out3[49].im = 0.0;
  out3[50].re = 0.0;
  out3[50].im = 0.0;
  out3[51].re = -t52 + t37 * t76_re;
  out3[51].im = t37 * t76_im;
  out3[52].re = t51 + t37 * t79_re;
  out3[52].im = t37 * t79_im;
  out3[53].re = t61.re + t37 * t82_re;
  out3[53].im = t61.im + t37 * t82_im;
  memcpy(&out2[0], &out3[0], 54U * sizeof(creal_T));
  t45 = t12 * t40;
  t61.re = t45 * t62.re;
  t61.im = t45 * t62.im;
  t84_re_tmp = t13 * t40;
  t84_re = t84_re_tmp * t62.re;
  t84_im = t84_re_tmp * t62.im;
  t148_re = t35 * t36;
  t4 = t148_re * t51;
  t94_re = t4 * t63.re;
  t94_im = t4 * t63.im;
  t5 = t12 * t35;
  t148_im = t5 * t36;
  t4 = t148_im * t38;
  t95_re = t4 * t63.re;
  t95_im = t4 * t63.im;
  t6 = t13 * t35;
  t19 = t6 * t36;
  t4 = t19 * t38;
  t96_re = t4 * t63.re;
  t96_im = t4 * t63.im;
  t4 = t148_re * t52;
  t97_re = t4 * t63.re;
  t97_im = t4 * t63.im;
  t57 = t35 * t37;
  t4 = t57 * t51;
  t98_re = t4 * t63.re;
  t98_im = t4 * t63.im;
  t4 = t148_im * t39;
  t99_re = t4 * t63.re;
  t99_im = t4 * t63.im;
  t9 = t5 * t37;
  t4 = t9 * t38;
  t100_re = t4 * t63.re;
  t100_im = t4 * t63.im;
  t4 = t19 * t39;
  t101_re = t4 * t63.re;
  t101_im = t4 * t63.im;
  t6 *= t37;
  t4 = t6 * t38;
  t102_re = t4 * t63.re;
  t102_im = t4 * t63.im;
  t4 = t148_re * t53;
  t103_re = t4 * t63.re;
  t103_im = t4 * t63.im;
  t4 = t57 * t52;
  t104_re = t4 * t63.re;
  t104_im = t4 * t63.im;
  t10 = t36 * t37;
  t4 = t10 * t51;
  t105_re = t4 * t63.re;
  t105_im = t4 * t63.im;
  t4 = t148_im * t40;
  t64_re = t4 * t63.re;
  t64_im = t4 * t63.im;
  t4 = t9 * t39;
  t62.re = t4 * t63.re;
  t62.im = t4 * t63.im;
  t148_re = t12 * t36 * t37;
  t4 = t148_re * t38;
  t108_re = t4 * t63.re;
  t108_im = t4 * t63.im;
  t4 = t19 * t40;
  t109_re = t4 * t63.re;
  t109_im = t4 * t63.im;
  t4 = t6 * t39;
  t110_re = t4 * t63.re;
  t110_im = t4 * t63.im;
  t5 = t13 * t36 * t37;
  t4 = t5 * t38;
  t111_re = t4 * t63.re;
  t111_im = t4 * t63.im;
  t4 = t57 * t53;
  t112_re = t4 * t63.re;
  t112_im = t4 * t63.im;
  t4 = t10 * t52;
  t113_re = t4 * t63.re;
  t113_im = t4 * t63.im;
  t4 = t9 * t40;
  t114_re = t4 * t63.re;
  t114_im = t4 * t63.im;
  t4 = t148_re * t39;
  t115_re = t4 * t63.re;
  t115_im = t4 * t63.im;
  t4 = t6 * t40;
  t116_re = t4 * t63.re;
  t116_im = t4 * t63.im;
  t4 = t5 * t39;
  t117_re = t4 * t63.re;
  t117_im = t4 * t63.im;
  t4 = t10 * t53;
  t118_re = t4 * t63.re;
  t118_im = t4 * t63.im;
  t4 = t148_re * t40;
  t119_re = t4 * t63.re;
  t119_im = t4 * t63.im;
  t4 = t5 * t40;
  t120_re = t4 * t63.re;
  t120_im = t4 * t63.im;
  t130_re = t21 + t64_re;
  t130_im = t64_im;
  t131_re = t21 + t62.re;
  t131_im = t62.im;
  t132_re = t21 + t108_re;
  t132_im = t108_im;
  t4 = t134_im * t41;
  t136_re = t77_re + t4 * t63.re;
  t136_im = t77_im + t4 * t63.im;
  t4 = t134_im * t42;
  t137_re = t77_re + t4 * t63.re;
  t137_im = t77_im + t4 * t63.im;
  t4 = t134_im * t43;
  t138_re = t77_re + t4 * t63.re;
  t138_im = t77_im + t4 * t63.im;
  t4 = t142_im * t41;
  t139_re = t80_re + t4 * t63.re;
  t139_im = t80_im + t4 * t63.im;
  t4 = t142_im * t42;
  t140_re = t80_re + t4 * t63.re;
  t140_im = t80_im + t4 * t63.im;
  t4 = t142_im * t43;
  t141_re = t80_re + t4 * t63.re;
  t141_im = t80_im + t4 * t63.im;
  t4 = t45 * t41;
  t142_re = t61.re + t4 * t63.re;
  t142_im = t61.im + t4 * t63.im;
  t4 = t45 * t42;
  t143_re = t61.re + t4 * t63.re;
  t40 = t61.im + t4 * t63.im;
  t4 = t45 * t43;
  t39 = t61.re + t4 * t63.re;
  t9 = t61.im + t4 * t63.im;
  t10 = t68_re + t99_re;
  t45 = t68_im + t99_im;
  t5 = t71_re + t95_re;
  t6 = t71_im + t95_im;
  t46 = t68_re + t114_re;
  t47 = t68_im + t114_im;
  t148_re = t74_re + t100_re;
  t148_im = t74_im + t100_im;
  t11 = t71_re + t119_re;
  t35 = t71_im + t119_im;
  t12 = t74_re + t115_re;
  t13 = t74_im + t115_im;
  t36 = t21 + -t64_re;
  t37 = -t64_im;
  t38 = t21 + -t62.re;
  t134_im = -t62.im;
  t19 = t21 + -t108_re;
  t57 = -t108_im;
  t108_re = t68_re + -t99_re;
  t108_im = t68_im + -t99_im;
  t80_re = t71_re + -t95_re;
  t80_im = t71_im + -t95_im;
  t77_re = t68_re + -t114_re;
  t77_im = t68_im + -t114_im;
  t62.re = t74_re + -t100_re;
  t62.im = t74_im + -t100_im;
  t64_re = t71_re + -t119_re;
  t64_im = t71_im + -t119_im;
  t61.re = t74_re + -t115_re;
  t61.im = t74_im + -t115_im;
  memset(&out3[0], 0, 21U * sizeof(creal_T));
  t4 = t41 * t51;
  out3[21].re = ((((in2[14] * (t70_re + t94_re) + in2[16] * (t73_re + t98_re)) +
                   t136_re * in2[13]) +
                  t5 * in2[15]) +
                 t148_re * in2[17]) +
                in2[12] * (t76_re + t4 * t63.re);
  out3[21].im = ((((in2[14] * (t70_im + t94_im) + in2[16] * (t73_im + t98_im)) +
                   t136_im * in2[13]) +
                  t6 * in2[15]) +
                 t148_im * in2[17]) +
                in2[12] * (t76_im + t4 * t63.im);
  t4 = t41 * t52;
  out3[22].re =
      ((((in2[16] * (t20 + t104_re) + t131_re * in2[17]) + t139_re * in2[13]) -
        t108_re * in2[15]) +
       in2[12] * (t79_re + t4 * t63.re)) -
      in2[14] * (t67_re - t97_re);
  out3[22].im =
      ((((in2[16] * t104_im + t131_im * in2[17]) + t139_im * in2[13]) -
        t108_im * in2[15]) +
       in2[12] * (t79_im + t4 * t63.im)) -
      in2[14] * (t67_im - t97_im);
  t4 = t41 * t53;
  out3[23].re = ((((-t36 * in2[15] + t142_re * in2[13]) - t77_re * in2[17]) +
                  in2[12] * (t82_re + t4 * t63.re)) -
                 in2[14] * (t20 - t103_re)) -
                in2[16] * (t67_re - t112_re);
  out3[23].im = ((((-t37 * in2[15] + t142_im * in2[13]) - t77_im * in2[17]) +
                  in2[12] * (t82_im + t4 * t63.im)) -
                 in2[14] * (0.0 - t103_im)) -
                in2[16] * (t67_im - t112_im);
  out3[24].re = 0.0;
  out3[24].im = 0.0;
  out3[25].re = 0.0;
  out3[25].im = 0.0;
  out3[26].re = 0.0;
  out3[26].im = 0.0;
  t4 = t78_re_tmp * t41;
  out3[27].re =
      ((((in2[15] * (t72_re + t96_re) + in2[17] * (t75_re + t102_re)) +
         t136_re * in2[12]) +
        t5 * in2[14]) +
       t148_re * in2[16]) +
      in2[13] * (t78_re + t4 * t63.re);
  out3[27].im =
      ((((in2[15] * (t72_im + t96_im) + in2[17] * (t75_im + t102_im)) +
         t136_im * in2[12]) +
        t6 * in2[14]) +
       t148_im * in2[16]) +
      in2[13] * (t78_im + t4 * t63.im);
  t4 = t81_re_tmp * t41;
  out3[28].re =
      ((((in2[17] * (t22 + t110_re) + t131_re * in2[16]) + t139_re * in2[12]) -
        t108_re * in2[14]) -
       in2[15] * (t69_re - t101_re)) +
      in2[13] * (t81_re + t4 * t63.re);
  out3[28].im =
      ((((in2[17] * t110_im + t131_im * in2[16]) + t139_im * in2[12]) -
        t108_im * in2[14]) -
       in2[15] * (t69_im - t101_im)) +
      in2[13] * (t81_im + t4 * t63.im);
  t4 = t84_re_tmp * t41;
  out3[29].re = ((((-t36 * in2[14] + t142_re * in2[12]) - t77_re * in2[16]) -
                  in2[15] * (t22 - t109_re)) -
                 in2[17] * (t69_re - t116_re)) +
                in2[13] * (t84_re + t4 * t63.re);
  out3[29].im = ((((-t37 * in2[14] + t142_im * in2[12]) - t77_im * in2[16]) -
                  in2[15] * (0.0 - t109_im)) -
                 in2[17] * (t69_im - t116_im)) +
                in2[13] * (t84_im + t4 * t63.im);
  out3[30].re = 0.0;
  out3[30].im = 0.0;
  out3[31].re = 0.0;
  out3[31].im = 0.0;
  out3[32].re = 0.0;
  out3[32].im = 0.0;
  t4 = t42 * t51;
  out3[33].re = ((((-t19 * in2[17] + t137_re * in2[15]) - t80_re * in2[13]) +
                  in2[14] * (t76_re + t4 * t63.re)) -
                 in2[16] * (t20 - t105_re)) -
                in2[12] * (t70_re - t94_re);
  out3[33].im = ((((-t57 * in2[17] + t137_im * in2[15]) - t80_im * in2[13]) +
                  in2[14] * (t76_im + t4 * t63.im)) -
                 in2[16] * (0.0 - t105_im)) -
                in2[12] * (t70_im - t94_im);
  t4 = t42 * t52;
  out3[34].re =
      ((((in2[12] * (t67_re + t97_re) + in2[16] * (t73_re + t113_re)) +
         t140_re * in2[15]) +
        t10 * in2[13]) +
       t12 * in2[17]) +
      in2[14] * (t79_re + t4 * t63.re);
  out3[34].im =
      ((((in2[12] * (t67_im + t97_im) + in2[16] * (t73_im + t113_im)) +
         t140_im * in2[15]) +
        t45 * in2[13]) +
       t13 * in2[17]) +
      in2[14] * (t79_im + t4 * t63.im);
  t4 = t42 * t53;
  out3[35].re =
      ((((in2[12] * (t20 + t103_re) + t130_re * in2[13]) + t143_re * in2[15]) -
        t64_re * in2[17]) +
       in2[14] * (t82_re + t4 * t63.re)) -
      in2[16] * (t70_re - t118_re);
  out3[35].im = ((((in2[12] * t103_im + t130_im * in2[13]) + t40 * in2[15]) -
                  t64_im * in2[17]) +
                 in2[14] * (t82_im + t4 * t63.im)) -
                in2[16] * (t70_im - t118_im);
  out3[36].re = 0.0;
  out3[36].im = 0.0;
  out3[37].re = 0.0;
  out3[37].im = 0.0;
  out3[38].re = 0.0;
  out3[38].im = 0.0;
  t4 = t78_re_tmp * t42;
  out3[39].re = ((((-t19 * in2[16] + t137_re * in2[14]) - t80_re * in2[12]) -
                  in2[17] * (t22 - t111_re)) -
                 in2[13] * (t72_re - t96_re)) +
                in2[15] * (t78_re + t4 * t63.re);
  out3[39].im = ((((-t57 * in2[16] + t137_im * in2[14]) - t80_im * in2[12]) -
                  in2[17] * (0.0 - t111_im)) -
                 in2[13] * (t72_im - t96_im)) +
                in2[15] * (t78_im + t4 * t63.im);
  t4 = t81_re_tmp * t42;
  out3[40].re =
      ((((in2[13] * (t69_re + t101_re) + in2[17] * (t75_re + t117_re)) +
         t140_re * in2[14]) +
        t10 * in2[12]) +
       t12 * in2[16]) +
      in2[15] * (t81_re + t4 * t63.re);
  out3[40].im =
      ((((in2[13] * (t69_im + t101_im) + in2[17] * (t75_im + t117_im)) +
         t140_im * in2[14]) +
        t45 * in2[12]) +
       t13 * in2[16]) +
      in2[15] * (t81_im + t4 * t63.im);
  t4 = t84_re_tmp * t42;
  out3[41].re =
      ((((in2[13] * (t22 + t109_re) + t130_re * in2[12]) + t143_re * in2[14]) -
        t64_re * in2[16]) -
       in2[17] * (t72_re - t120_re)) +
      in2[15] * (t84_re + t4 * t63.re);
  out3[41].im = ((((in2[13] * t109_im + t130_im * in2[12]) + t40 * in2[14]) -
                  t64_im * in2[16]) -
                 in2[17] * (t72_im - t120_im)) +
                in2[15] * (t84_im + t4 * t63.im);
  out3[42].re = 0.0;
  out3[42].im = 0.0;
  out3[43].re = 0.0;
  out3[43].im = 0.0;
  out3[44].re = 0.0;
  out3[44].im = 0.0;
  t4 = t43 * t51;
  out3[45].re =
      ((((in2[14] * (t20 + t105_re) + t132_re * in2[15]) + t138_re * in2[17]) -
        t62.re * in2[13]) +
       in2[16] * (t76_re + t4 * t63.re)) -
      in2[12] * (t73_re - t98_re);
  out3[45].im =
      ((((in2[14] * t105_im + t132_im * in2[15]) + t138_im * in2[17]) -
        t62.im * in2[13]) +
       in2[16] * (t76_im + t4 * t63.im)) -
      in2[12] * (t73_im - t98_im);
  t4 = t43 * t52;
  out3[46].re = ((((-t38 * in2[13] + t141_re * in2[17]) - t61.re * in2[15]) +
                  in2[16] * (t79_re + t4 * t63.re)) -
                 in2[12] * (t20 - t104_re)) -
                in2[14] * (t73_re - t113_re);
  out3[46].im =
      ((((-t134_im * in2[13] + t141_im * in2[17]) - t61.im * in2[15]) +
        in2[16] * (t79_im + t4 * t63.im)) -
       in2[12] * (0.0 - t104_im)) -
      in2[14] * (t73_im - t113_im);
  t4 = t43 * t53;
  out3[47].re =
      ((((in2[12] * (t67_re + t112_re) + in2[14] * (t70_re + t118_re)) +
         t46 * in2[13]) +
        t39 * in2[17]) +
       t11 * in2[15]) +
      in2[16] * (t82_re + t4 * t63.re);
  out3[47].im =
      ((((in2[12] * (t67_im + t112_im) + in2[14] * (t70_im + t118_im)) +
         t47 * in2[13]) +
        t9 * in2[17]) +
       t35 * in2[15]) +
      in2[16] * (t82_im + t4 * t63.im);
  out3[48].re = 0.0;
  out3[48].im = 0.0;
  out3[49].re = 0.0;
  out3[49].im = 0.0;
  out3[50].re = 0.0;
  out3[50].im = 0.0;
  t78_re_tmp *= t43;
  out3[51].re =
      ((((in2[15] * (t22 + t111_re) + t132_re * in2[14]) + t138_re * in2[16]) -
        t62.re * in2[12]) -
       in2[13] * (t75_re - t102_re)) +
      in2[17] * (t78_re + t78_re_tmp * t63.re);
  out3[51].im =
      ((((in2[15] * t111_im + t132_im * in2[14]) + t138_im * in2[16]) -
        t62.im * in2[12]) -
       in2[13] * (t75_im - t102_im)) +
      in2[17] * (t78_im + t78_re_tmp * t63.im);
  t81_re_tmp *= t43;
  out3[52].re = ((((-t38 * in2[12] + t141_re * in2[16]) - t61.re * in2[14]) -
                  in2[13] * (t22 - t110_re)) -
                 in2[15] * (t75_re - t117_re)) +
                in2[17] * (t81_re + t81_re_tmp * t63.re);
  out3[52].im =
      ((((-t134_im * in2[12] + t141_im * in2[16]) - t61.im * in2[14]) -
        in2[13] * (0.0 - t110_im)) -
       in2[15] * (t75_im - t117_im)) +
      in2[17] * (t81_im + t81_re_tmp * t63.im);
  t84_re_tmp *= t43;
  out3[53].re =
      ((((in2[13] * (t69_re + t116_re) + in2[15] * (t72_re + t120_re)) +
         t46 * in2[12]) +
        t39 * in2[16]) +
       t11 * in2[14]) +
      in2[17] * (t84_re + t84_re_tmp * t63.re);
  out3[53].im =
      ((((in2[13] * (t69_im + t116_im) + in2[15] * (t72_im + t120_im)) +
         t47 * in2[12]) +
        t9 * in2[16]) +
       t35 * in2[14]) +
      in2[17] * (t84_im + t84_re_tmp * t63.im);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
