function out1 = fj_vdF(in1,in2,s,ds,t_sym)
%fj_vdF
%    OUT1 = fj_vdF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Mar-2023 03:42:33

out1 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
