function [out1,out2,out3,out4,out5,out6,out7,out8,out9] = nqF(in1)
%nqF
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9] = nqF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Mar-2023 03:41:31

out1 = 9.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    out4 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 4
    out5 = 2.0;
end
if nargout > 5
    out6 = 1.0e+1;
end
if nargout > 6
    out7 = 0.0;
end
if nargout > 7
    out8 = 0.0;
end
if nargout > 8
    out9 = 1.0;
end
