function out1 = rjtipF(in1,in2,s,ds,t_sym)
%rjtipF
%    OUT1 = rjtipF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Mar-2023 03:42:33

l_f_ = in1(:,17);
l_s_ = in1(:,5);
lambda_ = in1(:,34);
q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
q4 = in2(4,:);
q5 = in2(5,:);
q6 = in2(6,:);
q7 = in2(7,:);
q8 = in2(8,:);
q9 = in2(9,:);
r_f_ = in1(:,18);
r_s2_ = in1(:,4);
t2 = NaN;
t3 = l_s_.*q4;
t4 = l_s_.*q6;
t5 = l_s_.*q8;
t6 = l_s_.^2;
t7 = s.^2;
t8 = s.*t3;
t9 = s.*t4;
t10 = s.*t5;
t11 = q1.*t6;
t12 = q2.*t6;
t13 = q3.*t6;
t14 = q5.*t6;
t15 = q7.*t6;
t16 = q9.*t6;
t17 = t7.*t14;
t18 = t7.*t15;
t19 = t7.*t16;
t20 = t3+t14;
t21 = t4+t15;
t22 = t5+t16;
t23 = t20.^2;
t24 = t21.^2;
t25 = t22.^2;
t26 = t8+t17;
t27 = t9+t18;
t28 = t10+t19;
t29 = -t23;
t30 = -t24;
t31 = -t25;
t32 = t29+t30+t31+1.0;
t33 = sqrt(t32);
out1 = reshape([t7.*t11,t11,t7.*t12,t12,l_s_.*s+t7.*t13,l_s_+t13,t2,t11+l_f_.*t20.*t22.*2.0+l_f_.*t21.*t33.*2.0,t2,t12+l_f_.*t21.*t22.*2.0-l_f_.*t20.*t33.*2.0,t2,l_s_+t13+l_f_.*t25+l_f_.*t29+l_f_.*t30-l_f_.*(t23+t24+t25-1.0),sqrt(-t26.^2-t27.^2-t28.^2+1.0),t33,t26,t20,t27,t21,t28,t22,t2,t33,t2,t20,t2,t21,t2,t22,1.0./sqrt(lambda_).*r_s2_,r_f_],[2,15]);
