function out1 = rksF(in1,in2,s,ds,t_sym)
%rksF
%    OUT1 = rksF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Mar-2023 03:42:33

out1 = zeros(0,0);
