function [out1,out2] = romF(in1,in2,s,ds,t_sym)
%romF
%    [OUT1,OUT2] = romF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Mar-2023 03:41:33

l_s_ = in1(:,5);
out1 = reshape([0.0,0.0,l_s_,0.0],[2,2]);
if nargout > 1
    out2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,l_s_,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[10,3]);
end
