function out1 = Tj_uF(in1,in2,s,ds,t_sym)
%Tj_uF
%    OUT1 = Tj_uF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Mar-2023 03:42:33

out1 = zeros(0,0);
