/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rjtipF.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo f_emlrtRSI = {
    53,       /* lineNo */
    "rjtipF", /* fcnName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\rjtipF.m" /* pathName */
};

static emlrtRSInfo g_emlrtRSI = {
    54,       /* lineNo */
    "rjtipF", /* fcnName */
    "D:\\R - Clemson\\SRA Program\\Simulation "
    "Package\\TMTDyn_2_Arm_Backpack\\V002\\eom\\rjtipF.m" /* pathName */
};

static emlrtRTEInfo emlrtRTEI = {
    13,     /* lineNo */
    9,      /* colNo */
    "sqrt", /* fName */
    "E:\\SOFTWARE\\DARK "
    "TECH\\MathWorks\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m" /* pName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[18],
            real_T s, real_T ds, real_T t_sym, real_T out1[30])
{
  emlrtStack st;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t26;
  real_T t27;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  (void)ds;
  (void)t_sym;
  st.prev = sp;
  st.tls = sp->tls;
  /* rjtipF */
  /*     OUT1 = rjtipF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.1.
   */
  /*     07-Mar-2023 03:42:33 */
  t3 = in2[3] * in1[4];
  t4 = in1[4] * in2[5];
  t5 = in1[4] * in2[7];
  t6 = in1[4] * in1[4];
  t7 = s * s;
  t11 = in2[0] * t6;
  t12 = in2[1] * t6;
  t13 = in2[2] * t6;
  t14 = in2[4] * t6;
  t15 = in2[6] * t6;
  t6 *= in2[8];
  t20 = t3 + t14;
  t21 = t4 + t15;
  t22 = t5 + t6;
  t23 = t20 * t20;
  t24 = t21 * t21;
  t25 = t22 * t22;
  t26 = s * t3 + t7 * t14;
  t27 = s * t4 + t7 * t15;
  t4 = s * t5 + t7 * t6;
  t15 = ((-t23 + -t24) + -t25) + 1.0;
  st.site = &f_emlrtRSI;
  if (t15 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t15 = muDoubleScalarSqrt(t15);
  st.site = &g_emlrtRSI;
  t5 = ((-(t26 * t26) - t27 * t27) - t4 * t4) + 1.0;
  if (t5 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t5 = muDoubleScalarSqrt(t5);
  st.site = &g_emlrtRSI;
  if (in1[33] < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  out1[0] = t7 * t11;
  out1[1] = t11;
  out1[2] = t7 * t12;
  out1[3] = t12;
  out1[4] = in1[4] * s + t7 * t13;
  t6 = in1[4] + t13;
  out1[5] = t6;
  out1[6] = rtNaN;
  t3 = in1[16] * t21;
  t14 = in1[16] * t20;
  out1[7] = (t11 + t14 * t22 * 2.0) + t3 * t15 * 2.0;
  out1[8] = rtNaN;
  out1[9] = (t12 + t3 * t22 * 2.0) - t14 * t15 * 2.0;
  out1[10] = rtNaN;
  out1[11] = (((t6 + in1[16] * t25) + in1[16] * -t23) + in1[16] * -t24) -
             in1[16] * (((t23 + t24) + t25) - 1.0);
  out1[12] = t5;
  out1[13] = t15;
  out1[14] = t26;
  out1[15] = t20;
  out1[16] = t27;
  out1[17] = t21;
  out1[18] = t4;
  out1[19] = t22;
  out1[20] = rtNaN;
  out1[21] = t15;
  out1[22] = rtNaN;
  out1[23] = t20;
  out1[24] = rtNaN;
  out1[25] = t21;
  out1[26] = rtNaN;
  out1[27] = t22;
  out1[28] = 1.0 / muDoubleScalarSqrt(in1[33]) * in1[3];
  out1[29] = in1[17];
}

/* End of code generation (rjtipF.c) */
